env:
  browser: true
  es2021: true,
  jest: true
extends:
  - airbnb-base
  - plugin:import/typescript
  - plugin:import/typescript
  - plugin:@typescript-eslint/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - "@typescript-eslint"
rules:
  import/extensions: "off"
  no-useless-constructor: "off"
  class-methods-use-this: "warn"
